# execute platform specific installation step

- name: install the required sytem packages
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - unzip
    - java-1.8.0-openjdk-devel