- name: check if the package is installed
  command: dpkg-query -W {{grafana_name}}
  register: grafana_check_installed
  failed_when: grafana_check_installed.rc > 1
  changed_when: grafana_check_installed.rc == 1

- name: create the distribution directory if not exist 
  file:
    path: "{{grafana_src_dir}}"
    state: directory
    recurse: yes    

- name: download the apt package
  get_url: 
    url="{{grafana_pkg_url}}"
    dest="{{grafana_src_dir}}"
  when: grafana_check_installed.rc == 1  

- name: install grafana apt package
  apt: deb="{{grafana_src_dir}}/{{grafana_pkg_name}}"
  when: grafana_check_installed.rc == 1  

- name: restart the service
  systemd:
    daemon_reload: yes
    state: restarted
    name: "{{ grafana_svc_name }}"    

- name: make sure the service is running
  systemd:
    state: started
    enabled: yes
    name: "{{ grafana_svc_name }}"